### PR TITLE
Update gems

### PR DESCRIPTION
**Pull request by mlenik**
I needed to add development gems group otherwise guard wasn't working correctly

### CODE REVIEW

**Comment by hleumas** [comment]
Can you explain that in a more detail? Is this a problem with this repo only, or do you have same problems with other handbooks too?

**Comment by mlenik** [comment]
There is a security issue with `ffi` gem older than 1.9.24 .. So I updated it including other gems (nothing was broken when I checked locally). The security alert is just in this repo, nonetheless it looks like also other handbooks need to be updated too.

On the other hand, the security issue is just on windows and as in production we don't use windows, I suppose we can dismiss the alert and close PR? https://github.com/vacuumlabs/coding-tips/network/alert/Gemfile.lock/ffi/open

**Comment by hleumas** [comment]
We might dismiss it, but I still don't understand this PR.

Why do we need to install additional packages below?

```
group :development, :test do
   gem 'pry'
   gem 'rb-readline'
 end
```

**Comment by mlenik** [comment]
Hmm, that was because of guard not working - this was the only way how I managed to get it working again.

**Pull request closed without merging**
